INPUTPATH_bmk: Z:/axioma_data/benchmark/000300/
INPUTPATH_alpha: Z:/axioma_data/alpha/
INPUTPATH_universe: Z:/axioma_data/universe/
INPUTPATH: Z:/RiskModel/
LOCAL_RISKMODEL: Z:/axioma_data/risk_model/
AxiomaDataDir: Z:/RiskModel/${yyyy}/${mm}/
initialReferenceValue: 1.0e8

OUTPUTPATH: E:/QUANT/R_code/output_uqer/


start_day: 20080401
end_day: 20171001
#stdfcf0,stdni0,pmom360 
#factor_name:  stdfcf0,stdni0,stoa,stom,stoq,Liquidity
#factor_name:  resvol,size,sizenl,liquqer,stoa,stoq,stom,Liquidity,pmom360,pmom640,pmom660,pmom940,pmom1220,stdfcf0,stdni0
factor_name: pmom360,pmom640,pmom660,pmom940,pmom1220
#
lag: 4
### flag control risk model data.  
#1 :choose uqer risk model  other number: choose axioma model
flag: 1


dirpath: Z:/backtest_data/output_uqer
outputpath: Z:/backtest_data/report_uqer
market_path: Z:/backtest_data/close_data/gogo_data


Benchmark: HS300
strategy_name: test_strategy
frequency: month 

# Constraints
budget:
    use: True
    Type: Limit Holding
    Max: 100
    Min: 100

stock_weight_limit:
    use: True 
    Max: 10
    Type: Limit AbsExposure

TE_limit:
    use: True
    Max: 5
    Type: Limit Risk
    
Limit_industry:
    use: True
    Max: 5
    Min: -5
    Type: Limit Exposure

Limit_size:
    use: False
    Max: 0.5
    Min: -0.5
    Type: Limit Exposure

Benchmark_holding:
    use: False
    Min: 80
    Type: Limit Holding 
